name: calling compostie action
on: [workflow_dispatch]
env:
  name: "Chaithanya"
  age: 25
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checking out the code."

      - name: Set Greeting
        run: |
          echo "Hello $INPUT_WHO_TO_GREET."
          echo "MY_VARIABLE=Hello World" >> "$GITHUB_ENV"

      - name: Random Number Generator
        id: one
        run:  |
          echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
          echo "$MY_VARIABLE"


      - name: output  
        run: |
          echo "Random number is ${{ steps.one.outputs.random-number }}"  



