name: calling compostie action
on: [workflow_dispatch]
env:
  name: "Chaithanya"
  age: 25
  INPUT_WHO_TO_GREET: "Chaithanya is greating to you"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Checking out the code."

      - name: Set Greeting
        run: |
          echo "Hello ${INPUT_WHO_TO_GREET}."
          echo "==========================="
          echo "::add-mask::${INPUT_WHO_TO_GREET}"
          echo "${{ env.INPUT_WHO_TO_GREET }}"
          echo "==========================="
          echo "MY_VARIABLE=Hello World" >> "$GITHUB_ENV"
          echo "::add-mask::$MY_VARIABLE"

      - name: Checking
        run: |
          echo "This is = $MY_VARIABLE "



