name: contex
on: [workflow_dispatch]
env:
  name: "Chaithanya"
  age: 25
  INPUT_WHO_TO_GREET: "Chaithanya is greating to you"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print github context
        run: echo "${{ toJSON(github) }}"

      - name: print env context
        run: printenv

      - name: Checking different
        run: |
          echo "run = ${{ GITHUB.ACTOR }}"
          echo "run2 = ${{ GITHUB.REF_PROTECTED }}"
          echo "run3 = ${{ github.env.name }}"