name: contex
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print github context
        run: echo "${{ toJSON(github) }}"

      - name: print env context
        run: echo "${{ toJSON(env) }}"  